language: c
env:
    - CFLAGS="-fprofile-arcs -ftest-coverage"
compiler:
    - gcc
    - clang
before_install:
    - sudo pip install cpp-coveralls
script:
    - make
    - make test
    - ./runecos
    - ./runecosexp
    - ./ecostester
    - ./ecos_bb_test
after_success:
    - coveralls --verbose --gcov-options '\-lp'
