init:
    - ps: "ls C:/Python*"

install:
    - ps: (new-object net.webclient).DownloadFile('Miniconda3-3.4.2-Windows-x86_64.exe', 'C:\miniconda.exe')
    - C:\miniconda.exe
    # - C:\Python27\Scripts\pip.exe install conda
    - C:\Python27\Scripts\conda.exe install numpy scipy

build_script:
    - cd python
    - python setup.py install
