environment:
    # trick environment into thinking it has vcvarsall.bat
    VS90COMNTOOLS: "%VS100COMNTOOLS%"
    matrix:
        - PYVER: 2.7
        - PYVER: 3.3
platform:
    - x86
    - x64
init:
    - "ECHO %VS90COMNTOOLS%"

install:
    - ps: (new-object net.webclient).DownloadFile('http://go.microsoft.com/?linkid=7729279', 'C:\msvc2008.exe')
    - ps: msiexec /i C:\msvc2008.exe /quiet /qn /norestart /log install.log
    - ps: (new-object net.webclient).DownloadFile('https://raw.github.com/pypa/pip/master/contrib/get-pip.py', 'C:\get-pip.py')
    - python C:\get-pip.py
    - C:\Python27\Scripts\pip.exe install conda
    - C:\Python27\Scripts\conda.exe init
    - C:\Python27\Scripts\conda.exe create -n build --yes --quiet python=%PYVER% numpy scipy nose

build_script:
    - cd python
    - C:\Python27\envs\build\python.exe setup.py install
