package:
  name: ecos

requirements:
  build:
    - python
    - numpy
    - setuptools
    - pip
    - scipy

  run:
    - python
    - numpy
    - scipy

test:
    requires:
        - nose
    commands:
        - nosetests python/test_interface.py
about:
  home: https://github.com/ifa-ethz/ecos
  license: GPLv3
  summary: Embedded cone solver for second-order cone programs
